---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      playwright:
        applies-to: version-updates
        dependency-type: "development"
        patterns:
          - 'playwright'
          - '@playwright/test'
      playwright-sec:
        applies-to: version-updates
        dependency-type: "development"
        patterns:
          - 'playwright'
          - '@playwright/test'
      typescript:
        applies-to: version-updates
        dependency-type: "development"
        patterns:
          - 'typescript'
        update-types:
          - major
          - minor
      typescript-sec:
        applies-to: version-updates
        dependency-type: "development"
        patterns:
          - 'typescript'
        update-types:
          - major
          - minor
      dev-non-breaking:
        applies-to: version-updates
        dependency-type: "development"
        patterns:
          - '*'
        update-types:
          - minor
          - patch
      dev-non-breaking-sec:
        applies-to: security-updates
        dependency-type: "development"
        patterns:
          - '*'
        update-types:
          - minor
          - patch
      prd-non-breaking:
        applies-to: version-updates
        dependency-type: "production"
        patterns:
          - '*'
        update-types:
          - minor
          - patch
      prd-non-breaking-sec:
        applies-to: security-updates
        dependency-type: "production"
        patterns:
          - '*'
        update-types:
          - minor
          - patch
