---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      dev-non-breaking:
        applies-to: version-updates
        dependency-type: "development"
        exclude-patterns:
          - '@playwright/test'
        patterns:
          - '*'
        update-types:
          - minor
          - patch
      dev-non-breaking-sec:
        applies-to: security-updates
        dependency-type: "development"
        exclude-patterns:
          - '@playwright/test'
        patterns:
          - '*'
        update-types:
          - minor
          - patch
      prd-non-breaking:
        applies-to: version-updates
        dependency-type: "production"
        exclude-patterns:
          - '@playwright/test'
        patterns:
          - '*'
        update-types:
          - minor
          - patch
      prd-non-breaking-sec:
        applies-to: security-updates
        dependency-type: "production"
        exclude-patterns:
          - '@playwright/test'
        patterns:
          - '*'
        update-types:
          - minor
          - patch
